# my bashrc file
source /Users/sonic/bin/dotfiles/bash/env
source /Users/sonic/bin/dotfiles/bash/alias
source /Users/sonic/bin/dotfiles/bash/prompt

function parse_git_dirty {
 [[ $(git status 2> /dev/null | tail -n1) != "nothing to commit (working directory clean)" ]] && echo "*"
}
function parse_git_branch {
 git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/[\1$(parse_git_dirty)]/"
}
